# Generated by Django 3.0.7 on 2023-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='gstin',
        ),
        migrations.AddField(
            model_name='salebill',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
